server:
  port: 8080
  servlet:
    context-path: /
spring:
  # 环境 dev|test|prod
  profiles:
    active: local
  application:
    name: Xx
  datasource:
    url: jdbc:sqlite:D:/WORK/database/xx_test.db
    username: root
    password: 1qaz2wsx
    driver-class-name: org.sqlite.JDBC
  thymeleaf:
    prefix: classpath:/web/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    mode: HTML
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths: /*
  savepath: d://tmp//tmp//
