server:
  port: 8080
  servlet:
    context-path: /
spring:
  # 环境 dev|test|prod
  profiles:
    active: local
  application:
    name: NMDM
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true   #这里设置enable,其配置文件默认会被读取到MultipartConfigElement中
      file-size-threshold: 400MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    prefix: classpath:/web/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    mode: HTML
    #    热部署
  devtools:
    restart:
    #      是否启用重启
      enabled: true
      #      设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      spring.devtools.restart.exclude: WEB-INF/**
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /*
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    database: 0
#    password:
#    host: 127.0.0.1
#    port: 6389
#    lettuce:
#      pool:
#        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 100 # 连接池中的最大空闲连接
#        min-idle: 50 # 连接池中的最小空闲连接
#        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    timeout: 1000

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.cn.xx.test.mybatis

#配置日志
logging:
  config: classpath:logback-spring.xml

skipTests: true