package com.cn.xx.test.mybaties.modle;

public class Info {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.i_type
     *
     * @mbg.generated
     */
    private String iType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.created
     *
     * @mbg.generated
     */
    private String created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.imgs
     *
     * @mbg.generated
     */
    private String imgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_info.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.id
     *
     * @return the value of m_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.id
     *
     * @param id the value for m_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.uid
     *
     * @return the value of m_info.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.uid
     *
     * @param uid the value for m_info.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.i_type
     *
     * @return the value of m_info.i_type
     *
     * @mbg.generated
     */
    public String getiType() {
        return iType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.i_type
     *
     * @param iType the value for m_info.i_type
     *
     * @mbg.generated
     */
    public void setiType(String iType) {
        this.iType = iType == null ? null : iType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.name
     *
     * @return the value of m_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.name
     *
     * @param name the value for m_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.price
     *
     * @return the value of m_info.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.price
     *
     * @param price the value for m_info.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.remark
     *
     * @return the value of m_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.remark
     *
     * @param remark the value for m_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.created
     *
     * @return the value of m_info.created
     *
     * @mbg.generated
     */
    public String getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.created
     *
     * @param created the value for m_info.created
     *
     * @mbg.generated
     */
    public void setCreated(String created) {
        this.created = created == null ? null : created.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.imgs
     *
     * @return the value of m_info.imgs
     *
     * @mbg.generated
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.imgs
     *
     * @param imgs the value for m_info.imgs
     *
     * @mbg.generated
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_info.state
     *
     * @return the value of m_info.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_info.state
     *
     * @param state the value for m_info.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}